# Generated by Django 5.0.4 on 2024-05-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='data',
        ),
    ]
