# Generated by Django 5.0.4 on 2024-05-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_data_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default/image.jpg', upload_to='images/'),
        ),
    ]
