# Generated by Django 5.0.4 on 2024-05-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='media/images/image.jpg', upload_to='images/'),
        ),
    ]
