# Generated by Django 4.2.7 on 2024-05-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_slug_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
